#ifndef BPLC_errorCodes_h
#define BPLC_errorCodes_h
#include "Arduino.h"
//Bei änderungen immer auch MOT11 Firmware updaten, da sonst Fehler falsch interpretiert werden!!!
//case BPLC ERROR TYPE
typedef enum
{    
    BPLC_ERROR__NO_ERROR,
    //MCU Errors
    BPLC_ERROR__NO_MCU_DEFINED,
    BPLC_ERROR__BPLC_BEGIN_CALL_MISSING,
    BPLC_ERROR__OLED_COMMUNICATION_FAILED,
    BPLC_ERROR__RUNNTIME,
    BPLC_ERROR__COMMUNICATION_FAILED,
    BPLC_ERROR__NETWORK_ADDRESS_NOT_DEFINED,
    BPLC_ERROR__UNDEFINED_I2C_DEVICE_FOUND,
    BPLC_ERROR__FLASH_PARAMETER_CORUPT,
    //ExtensonCardManager Errors    
    ECM_ERROR__EC_NOT_DEFINED,
    ECM_ERROR__EC_ALREADY_DEFINED,
    //MCU11 errors
    MCU11_ERROR__CHANNEL_OUT_OF_RANGE,
    MCU11_ERROR__CHANNEL_POINTER_NOT_SET,
    //DIN11 errors
    DIN11_ERROR__I2C_CONNECTION_FAILED, 
    DIN11_ERROR__I2C_ADDRESS_OUT_OF_RANGE, 
    DIN11_ERROR__UNDEFINED_DIN11_FOUND,
    DIN11_ERROR__NO_CHANNEL_IN_USE,
    DIN11_ERROR__CHANNEL_ALREADY_IN_USE,
    DIN11_ERROR__ALL_CHANNELS_ALREADY_IN_USE,   
    DIN11_ERROR__CHANNEL_OUT_OF_RANGE,
    DIN11_ERROR__IO_OBJECT_NOT_SUITABLE,   
    //AIN11 errors
    AIN11_ERROR__I2C_CONNECTION_FAILED, 
    AIN11_ERROR__I2C_ADDRESS_OUT_OF_RANGE,
    AIN11_ERROR__UNDEFINED_AIN11_FOUND,
    AIN11_ERROR__NO_CHANNEL_IN_USE,
    AIN11_ERROR__CHANNEL_ALREADY_IN_USE,
    AIN11_ERROR__ALL_CHANNELS_ALREADY_IN_USE,   
    AIN11_ERROR__CHANNEL_OUT_OF_RANGE,
    AIN11_ERROR__IO_OBJECT_NOT_SUITABLE,
    //REL11 errors
    REL11_ERROR__I2C_CONNECTION_FAILED, 
    REL11_ERROR__I2C_ADDRESS_OUT_OF_RANGE, 
    REL11_ERROR__UNDEFINED_REL11_FOUND,
    REL11_ERROR__NO_CHANNEL_IN_USE,
    REL11_ERROR__CHANNEL_ALREADY_IN_USE,
    REL11_ERROR__ALL_CHANNELS_ALREADY_IN_USE,   
    REL11_ERROR__CHANNEL_OUT_OF_RANGE,
    REL11_ERROR__IO_OBJECT_NOT_SUITABLE,
    //DO11 errors
    DO11_ERROR__I2C_CONNECTION_FAILED, 
    DO11_ERROR__I2C_ADDRESS_OUT_OF_RANGE, 
    DO11_ERROR__UNDEFINED_DO11_FOUND,
    DO11_ERROR__NO_CHANNEL_IN_USE,
    DO11_ERROR__CHANNEL_ALREADY_IN_USE,
    DO11_ERROR__ALL_CHANNELS_ALREADY_IN_USE,   
    DO11_ERROR__CHANNEL_OUT_OF_RANGE,
    DO11_ERROR__IO_OBJECT_NOT_SUITABLE,
    //FUSE11 errors
    FUSE12_ERROR__I2C_CONNECTION_FAILED, 
    FUSE12_ERROR__I2C_ADDRESS_OUT_OF_RANGE, 
    FUSE12_ERROR__UNDEFINED_FUSE12_FOUND,
    FUSE12_ERROR__NO_CHANNEL_IN_USE,
    FUSE12_ERROR__CHANNEL_ALREADY_IN_USE,
    FUSE12_ERROR__ALL_CHANNELS_ALREADY_IN_USE,   
    FUSE12_ERROR__CHANNEL_OUT_OF_RANGE,
    FUSE12_ERROR__IO_OBJECT_NOT_SUITABLE,
    //NANO11 errors
    NANO11_ERROR__I2C_CONNECTION_FAILED, 
    NANO11_ERROR__I2C_ADDRESS_OUT_OF_RANGE, 
    NANO11_ERROR__UNDEFINED_NANO11_FOUND,
    NANO11_ERROR__NO_CHANNEL_IN_USE,
    NANO11_ERROR__CHANNEL_ALREADY_IN_USE,
    NANO11_ERROR__ALL_CHANNELS_ALREADY_IN_USE,   
    NANO11_ERROR__CHANNEL_OUT_OF_RANGE,
    NANO11_ERROR__IO_OBJECT_NOT_SUITABLE,
    //MOT11 errors
    MOT11_ERROR__I2C_CONNECTION_FAILED, 
    MOT11_ERROR__I2C_ADDRESS_OUT_OF_RANGE, 
    MOT11_ERROR__UNDEFINED_MOT11_FOUND,
    MOT11_ERROR__NO_CHANNEL_IN_USE,
    MOT11_ERROR__CHANNEL_ALREADY_IN_USE,
    MOT11_ERROR__ALL_CHANNELS_ALREADY_IN_USE,   
    MOT11_ERROR__CHANNEL_OUT_OF_RANGE,
    MOT11_ERROR__IO_OBJECT_NOT_SUITABLE,
    MOT11_ERROR__RECEIVED_DRIVE_PARAMETER_NOT_PLAUSIBLE, 
    MOT11_ERROR__OVER_CURRENT,
    MOT11_ERROR__OVER_CURRENT_NOT_USED_1,
    MOT11_ERROR__OVER_CURRENT_NOT_USED_2,
    MOT11_ERROR__OVER_TEMPERATURE,   
    MOT11_ERROR__CURRENT_NOT_TEACHED, 
    MOT11_ERROR__OEN_DISABLED,
    //TMP11 errors
    TMP11_ERROR__I2C_CONNECTION_FAILED, 
    TMP11_ERROR__I2C_ADDRESS_OUT_OF_RANGE, 
    TMP11_ERROR__UNDEFINED_TMP11_FOUND,
    TMP11_ERROR__NO_CHANNEL_IN_USE,
    TMP11_ERROR__CHANNEL_ALREADY_IN_USE,
    TMP11_ERROR__ALL_CHANNELS_ALREADY_IN_USE,   
    TMP11_ERROR__CHANNEL_OUT_OF_RANGE,
    TMP11_ERROR__IO_OBJECT_NOT_SUITABLE,
    //PPO11 errors
    PPO11_ERROR__I2C_CONNECTION_FAILED, 
    PPO11_ERROR__I2C_ADDRESS_OUT_OF_RANGE, 
    PPO11_ERROR__UNDEFINED_PPO11_FOUND,
    PPO11_ERROR__NO_CHANNEL_IN_USE,
    PPO11_ERROR__CHANNEL_ALREADY_IN_USE,
    PPO11_ERROR__ALL_CHANNELS_ALREADY_IN_USE,   
    PPO11_ERROR__CHANNEL_OUT_OF_RANGE,
    PPO11_ERROR__IO_OBJECT_NOT_SUITABLE,

    BPLC_ERROR__COUNT,
}e_BPLC_ERROR_t;



class ERROR_errorText
{
    public:
    ERROR_errorText(){};

    String ERROR_CODE_TEXT[BPLC_ERROR__COUNT]=
    {
        {"BPLC_ERROR__NO_ERROR"},
        //MCU Errors
        {"BPLC_ERROR__NO_MCU_DEFINED"},
        {"BPLC_ERROR__BPLC_BEGIN_CALL_MISSING"},
        {"BPLC_ERROR__OLED_COMMUNICATION_FAILED"},
        {"BPLC_ERROR__RUNNTIME"},
        {"BPLC_ERROR__COMMUNICATION_FAILED"},
        {"BPLC_ERROR__NETWORK_ADDRESS_NOT_DEFINED"},
        {"BPLC_ERROR__UNDEFINED_I2C_DEVICE_FOUND"},
        {"BPLC_ERROR__FLASH_PARAMETER_CORUPT"},
        //ExtensonCardManager Errors    
        {"ECM_ERROR__EC_NOT_DEFINED"},
        {"ECM_ERROR__EC_ALREADY_DEFINED"},
        //MCU11 errors
        {"MCU11_ERROR__CHANNEL_OUT_OF_RANGE"},
        {"MCU11_ERROR__CHANNEL_POINTER_NOT_SET"},
        //DIN11 errors
        {"DIN11_ERROR__I2C_CONNECTION_FAILED"}, 
        {"DIN11_ERROR__I2C_ADDRESS_OUT_OF_RANGE"}, 
        {"DIN11_ERROR__UNDEFINED_DIN11_FOUND"},
        {"DIN11_ERROR__NO_CHANNEL_IN_USE"},
        {"DIN11_ERROR__CHANNEL_ALREADY_IN_USE"},
        {"DIN11_ERROR__ALL_CHANNELS_ALREADY_IN_USE"},   
        {"DIN11_ERROR__CHANNEL_OUT_OF_RANGE"},
        {"DIN11_ERROR__IO_OBJECT_NOT_SUITABLE"},   
        //AIN11 errors
        {"AIN11_ERROR__I2C_CONNECTION_FAILED"}, 
        {"AIN11_ERROR__I2C_ADDRESS_OUT_OF_RANGE"},
        {"AIN11_ERROR__UNDEFINED_AIN11_FOUND"},
        {"AIN11_ERROR__NO_CHANNEL_IN_USE"},
        {"AIN11_ERROR__CHANNEL_ALREADY_IN_USE"},
        {"AIN11_ERROR__ALL_CHANNELS_ALREADY_IN_USE"},   
        {"AIN11_ERROR__CHANNEL_OUT_OF_RANGE"},
        {"AIN11_ERROR__IO_OBJECT_NOT_SUITABLE"},
        //REL11 errors
        {"REL11_ERROR__I2C_CONNECTION_FAILED"}, 
        {"REL11_ERROR__I2C_ADDRESS_OUT_OF_RANGE"}, 
        {"REL11_ERROR__UNDEFINED_REL11_FOUND"},
        {"REL11_ERROR__NO_CHANNEL_IN_USE"},
        ("REL11_ERROR__CHANNEL_ALREADY_IN_USE"),
        {"REL11_ERROR__ALL_CHANNELS_ALREADY_IN_USE"},   
        {"REL11_ERROR__CHANNEL_OUT_OF_RANGE"},
        {"REL11_ERROR__IO_OBJECT_NOT_SUITABLE"},
        //DO11 errors
        {"DO11_ERROR__I2C_CONNECTION_FAILED"}, 
        {"DO11_ERROR__I2C_ADDRESS_OUT_OF_RANGE"}, 
        {"DO11_ERROR__UNDEFINED_DO11_FOUND"},
        {"DO11_ERROR__NO_CHANNEL_IN_USE"},
        {"DO11_ERROR__CHANNEL_ALREADY_IN_USE"},
        {"DO11_ERROR__ALL_CHANNELS_ALREADY_IN_USE"},   
        {"DO11_ERROR__CHANNEL_OUT_OF_RANGE"},
        {"DO11_ERROR__IO_OBJECT_NOT_SUITABLE"},
        //FUSE11 errors
        {"FUSE12_ERROR__I2C_CONNECTION_FAILED"}, 
        {"FUSE12_ERROR__I2C_ADDRESS_OUT_OF_RANGE"}, 
        {"FUSE12_ERROR__UNDEFINED_FUSE12_FOUND"},
        {"FUSE12_ERROR__NO_CHANNEL_IN_USE"},
        {"FUSE12_ERROR__CHANNEL_ALREADY_IN_USE"},
        {"FUSE12_ERROR__ALL_CHANNELS_ALREADY_IN_USE"},   
        {"FUSE12_ERROR__CHANNEL_OUT_OF_RANGE"},
        {"FUSE12_ERROR__IO_OBJECT_NOT_SUITABLE"},
        //NANO11 errors
        {"NANO11_ERROR__I2C_CONNECTION_FAILED"}, 
        {"NANO11_ERROR__I2C_ADDRESS_OUT_OF_RANGE"}, 
        {"NANO11_ERROR__UNDEFINED_NANO11_FOUND"},
        {"NANO11_ERROR__NO_CHANNEL_IN_USE"},
        {"NANO11_ERROR__CHANNEL_ALREADY_IN_USE"},
        {"NANO11_ERROR__ALL_CHANNELS_ALREADY_IN_USE"},   
        {"NANO11_ERROR__CHANNEL_OUT_OF_RANGE"},
        {"NANO11_ERROR__IO_OBJECT_NOT_SUITABLE"},
        //MOT11 errors
        {"MOT11_ERROR__I2C_CONNECTION_FAILED"}, 
        {"MOT11_ERROR__I2C_ADDRESS_OUT_OF_RANGE"}, 
        {"MOT11_ERROR__UNDEFINED_MOT11_FOUND"},
        {"MOT11_ERROR__NO_CHANNEL_IN_USE"},
        {"MOT11_ERROR__CHANNEL_ALREADY_IN_USE"},
        {"MOT11_ERROR__ALL_CHANNELS_ALREADY_IN_USE"},   
        {"MOT11_ERROR__CHANNEL_OUT_OF_RANGE"},
        {"MOT11_ERROR__IO_OBJECT_NOT_SUITABLE"},
        {"MOT11_ERROR__RECEIVED_DRIVE_PARAMETER_NOT_PLAUSIBLE"}, 
        {"MOT11_ERROR__OVER_CURRENT"},
        {"MOT11_ERROR__OVER_CURRENT_NOT_USED"},
        {"MOT11_ERROR__OVER_CURRENT_NOT_USED"},
        {"MOT11_ERROR__OVER_TEMPERATURE"},   
        {"MOT11_ERROR__CURRENT_NOT_TEACHED"}, 
        {"MOT11_ERROR__OEN_DISABLED"},
        //TMP11 errors
        {"TMP11_ERROR__I2C_CONNECTION_FAILED"}, 
        {"TMP11_ERROR__I2C_ADDRESS_OUT_OF_RANGE"}, 
        {"TMP11_ERROR__UNDEFINED_TMP11_FOUND"},
        {"TMP11_ERROR__NO_CHANNEL_IN_USE"},
        {"TMP11_ERROR__CHANNEL_ALREADY_IN_USE"},
        {"TMP11_ERROR__ALL_CHANNELS_ALREADY_IN_USE"},   
        {"TMP11_ERROR__CHANNEL_OUT_OF_RANGE"},
        {"TMP11_ERROR__IO_OBJECT_NOT_SUITABLE"},
        //PPO11 errors
        {"PPO11_ERROR__I2C_CONNECTION_FAILED"}, 
        {"PPO11_ERROR__I2C_ADDRESS_OUT_OF_RANGE"}, 
        {"PPO11_ERROR__UNDEFINED_PPO11_FOUND"},
        {"PPO11_ERROR__NO_CHANNEL_IN_USE"},
        {"PPO11_ERROR__CHANNEL_ALREADY_IN_USE"},
        {"PPO11_ERROR__ALL_CHANNELS_ALREADY_IN_USE"},   
        {"PPO11_ERROR__CHANNEL_OUT_OF_RANGE"},
        {"PPO11_ERROR__IO_OBJECT_NOT_SUITABLE"},
    };

    String getErrorCodeText(const e_BPLC_ERROR_t ERROR_CODE)
    {      
        if(BPLC_ERROR__COUNT != 92)
        {
            return("ERROR_TEXTS_NEED_UPDATE!");
        }
        else
        {
            return ERROR_CODE_TEXT[ERROR_CODE];
        }          
    }       
};
#endif