#ifndef BPLC_ERRORS_h
#define BPLC_ERRORS_h

//BPLC ERROR TYPE
typedef enum
{    
    BPLC_ERROR__NO_ERROR,
    //MCU Errors
    BPLC_ERROR__OLED_COMMUNICATION_FAILED,
    BPLC_ERROR__RUNNTIME,
    //DIN11 errors
    DIN11_ERROR__I2C_CONNECTION_FAILED, 
    DIN11_ERROR__PORT_ALREADY_DEFINED,
    DIN11_ERROR__PORT_OVERFLOW,   
    //AIN11 errors
    AIN11_ERROR__I2C_CONNECTION_FAILED, 
    AIN11_ERROR__PORT_ALREADY_DEFINED,
    AIN11_ERROR__PORT_OVERFLOW,
    //REL11 errors
    REL11_ERROR__I2C_CONNECTION_FAILED, 
    REL11_ERROR__PORT_ALREADY_DEFINED,
    REL11_ERROR__PORT_OVERFLOW,
    //DO11 errors
    DO11_ERROR__I2C_CONNECTION_FAILED, 
    DO11_ERROR__PORT_ALREADY_DEFINED,
    DO11_ERROR__PORT_OVERFLOW,
    //FUSE11 errors
    FUSE11_ERROR__I2C_CONNECTION_FAILED, 
    FUSE11_ERROR__PORT_ALREADY_DEFINED,
    FUSE11_ERROR__PORT_OVERFLOW,
    //NANO11 errors
    NANO11_ERROR__I2C_CONNECTION_FAILED, 
    NANO11_ERROR__PORT_ALREADY_DEFINED,
    NANO11_ERROR__PORT_OVERFLOW,
    //MOT11 errors
    MOT11_ERROR__I2C_CONNECTION_FAILED,
    MOT11_ERROR__RECEIVED_DRIVE_PARAMETER_NOT_PLAUSIBLE, 
    MOT11_ERROR__OVER_CURRENT,
    MOT11_ERROR__OVER_TEMPERATURE,   
    MOT11_ERROR__CURRENT_NOT_TEACHED, 
    MOT11_ERROR__OEN_DISABLED,
    MOT11_ERROR__PORT_ALREADY_DEFINED,
    MOT11_ERROR__PORT_OVERFLOW,
    MOT11_ERROR__COUNT,

    BPLC_ERROR__COUNT,
}e_BPLC_ERROR_t;


#endif