#ifndef BPLC_CARDS_h
#define BPLC_CARDS_h

//--------------------------------------------------------------------
//Version und Revision
//--------------------------------------------------------------------
typedef enum
{
    MCU_CARD__NO_MCU_DEFINED,
    MCU_CARD__MCU11revA,
    MCU_CARD__MCU11revB,

}e_MCU_CARD_TYPE_t;

typedef enum
{
    EXTENSION_CARD__NO_CARD_DEFINED,
    
    EXTENSION_CARD__DIN11revA_1,
    EXTENSION_CARD__DIN11revA_2,
    EXTENSION_CARD__DIN11revA_3,
    EXTENSION_CARD__DIN11revA_4,

    EXTENSION_CARD__DO11revA_1,
    EXTENSION_CARD__DO11revA_2,
    EXTENSION_CARD__DO11revA_3,
    EXTENSION_CARD__DO11revA_4,

    EXTENSION_CARD__AIN11revA_1,
    EXTENSION_CARD__AIN11revA_2,
    EXTENSION_CARD__AIN11revA_3,
    EXTENSION_CARD__AIN11revA_4,

    EXTENSION_CARD__REL11revA_1,
    EXTENSION_CARD__REL11revA_2,
    EXTENSION_CARD__REL11revA_3,
    EXTENSION_CARD__REL11revA_4,

    EXTENSION_CARD__MOT11revA_1,
    EXTENSION_CARD__MOT11revA_2,
    EXTENSION_CARD__MOT11revA_3,
    EXTENSION_CARD__MOT11revA_4,

    EXTENSION_CARD__NANO11revA_1,
    EXTENSION_CARD__NANO11revA_2,
    EXTENSION_CARD__NANO11revA_3,
    EXTENSION_CARD__NANO11revA_4,
    
    EXTENSION_CARD__FUSE11revA_1,
    EXTENSION_CARD__FUSE11revA_2,
    EXTENSION_CARD__FUSE11revA_3,
    EXTENSION_CARD__FUSE11revA_4,

    EXTENSION_CARD__FUSE12revA_1,
    EXTENSION_CARD__FUSE12revA_2,
    EXTENSION_CARD__FUSE12revA_3,
    EXTENSION_CARD__FUSE12revA_4,

    EXTENSION_CARD__TYPE_COUNT,

}e_EXTENSION_CARD_TYPE_t;
#endif